### ISSUE TITLE
Invalid Password

### ISSUE THREAD

**Issue by shearpaladin** [CMPUT301F19T27/FindMyFeelings#29]
typing in a password without the specified format:
ex- signing up and just putting your name as your password will put you in the database but you will tell you sign up failed.

**Comment by shearpaladin** [comment]
The issue also persists if we have password: 
12345

POSSBIBLE FIX: we should specify the password length and characters needed.

**Comment by shearpaladin** [comment]
Evidence:
![image](https://user-images.githubusercontent.com/46476399/68078882-17120980-fda5-11e9-9a4a-a1b2e81675ab.png)

**Comment by shearpaladin** [comment]
We can see below these users are no authorized:
![image](https://user-images.githubusercontent.com/46476399/68078885-2bee9d00-fda5-11e9-9bf6-308308e37952.png)

**Comment by nevilkandathil** [comment]
First issue fixed. Invalid sign up does not create user data on firestore.
For the password issue, I guess firestore password criteria is always a alphabet and a digit
